from PyQt6 import QtCore, QtGui, QtWidgets
from DDC import DatabaseDownloderConnector

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 81, 95))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 81, 95))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 1221, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1221, 671))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1219, 669))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1221, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 81, 95))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 81, 95))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        self.label.setPalette(palette)
        self.label.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.year_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.year_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout_3.addWidget(self.year_label)
        self.from_date = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget)
        self.from_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 2), QtCore.QTime(0, 0, 0)))
        self.from_date.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 12, 31), QtCore.QTime(22, 59, 59)))
        self.from_date.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(1, 0, 0)))
        self.from_date.setMaximumDate(QtCore.QDate(2023, 12, 31))
        self.from_date.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.from_date.setCalendarPopup(True)
        self.from_date.setObjectName("from_date")
        self.horizontalLayout_3.addWidget(self.from_date)
        self.month_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.month_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.month_label.setObjectName("month_label")
        self.horizontalLayout_3.addWidget(self.month_label)
        self.to_date = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget)
        self.to_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 2), QtCore.QTime(0, 0, 0)))
        self.to_date.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 12, 31), QtCore.QTime(22, 59, 59)))
        self.to_date.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.to_date.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.to_date.setCalendarPopup(True)
        self.to_date.setObjectName("to_date")
        self.horizontalLayout_3.addWidget(self.to_date)
        self.increment_checkbox = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increment_checkbox.sizePolicy().hasHeightForWidth())
        self.increment_checkbox.setSizePolicy(sizePolicy)
        self.increment_checkbox.setChecked(True)
        self.increment_checkbox.setObjectName("increment_checkbox")
        self.horizontalLayout_3.addWidget(self.increment_checkbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.download_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.download_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.download_button.setFlat(False)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_2.addWidget(self.download_button)
        self.delete_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.insert_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.insert_button.setObjectName("insert_button")
        self.horizontalLayout_2.addWidget(self.insert_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 81, 95))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 81, 95))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 104))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 74, 86))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 105))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        self.label_2.setPalette(palette)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.year_label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.year_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.year_label_2.setObjectName("year_label_2")
        self.horizontalLayout_4.addWidget(self.year_label_2)
        self.from_date_analyze = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget)
        self.from_date_analyze.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 2), QtCore.QTime(0, 0, 0)))
        self.from_date_analyze.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 12, 31), QtCore.QTime(21, 59, 59)))
        self.from_date_analyze.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(23, 0, 0)))
        self.from_date_analyze.setMaximumDate(QtCore.QDate(2023, 12, 31))
        self.from_date_analyze.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.from_date_analyze.setCalendarPopup(True)
        self.from_date_analyze.setObjectName("from_date_analyze")
        self.horizontalLayout_4.addWidget(self.from_date_analyze)
        self.month_label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.month_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.month_label_2.setObjectName("month_label_2")
        self.horizontalLayout_4.addWidget(self.month_label_2)
        self.to_date_analyze = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget)
        self.to_date_analyze.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 2), QtCore.QTime(0, 0, 0)))
        self.to_date_analyze.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 12, 31), QtCore.QTime(21, 59, 59)))
        self.to_date_analyze.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2014, 12, 31), QtCore.QTime(23, 0, 0)))
        self.to_date_analyze.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.to_date_analyze.setCalendarPopup(True)
        self.to_date_analyze.setObjectName("to_date_analyze")
        self.horizontalLayout_4.addWidget(self.to_date_analyze)
        spacerItem2 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.analyze_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.analyze_button.setObjectName("analyze_button")
        self.verticalLayout_5.addWidget(self.analyze_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.from_date, self.to_date)
        MainWindow.setTabOrder(self.to_date, self.increment_checkbox)
        MainWindow.setTabOrder(self.increment_checkbox, self.download_button)
        MainWindow.setTabOrder(self.download_button, self.delete_button)
        MainWindow.setTabOrder(self.delete_button, self.insert_button)
        MainWindow.setTabOrder(self.insert_button, self.scrollArea)
        
        self.from_date.dateChanged.connect(self.from_time_changed)
        self.from_date_analyze.dateChanged.connect(self.from_time_changed_analyze)
        self.increment_checkbox.stateChanged.connect(self.increment_changed)
        self.ddc = DatabaseDownloderConnector()
        self.download_button.clicked.connect(self.download_files)
        self.delete_button.clicked.connect(self.delete_files)
        self.insert_button.clicked.connect(self.load_files_into_database)
        self.analyze_button.clicked.connect(self.analyze_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Datenanalyse Projekt"))
        self.label.setText(_translate("MainWindow", "# Datei Download auswahl"))
        self.year_label.setText(_translate("MainWindow", "Von:"))
        self.month_label.setText(_translate("MainWindow", "Bis:"))
        self.increment_checkbox.setText(_translate("MainWindow", "Hochzählen"))
        self.download_button.setText(_translate("MainWindow", "Dateien Herunterunterladen"))
        self.delete_button.setText(_translate("MainWindow", "Dateien Löschen"))
        self.insert_button.setText(_translate("MainWindow", "Dateien in die Datenbank laden"))
        self.label_2.setText(_translate("MainWindow", "# Verarbeitungs bereich"))
        self.year_label_2.setText(_translate("MainWindow", "Von:"))
        self.month_label_2.setText(_translate("MainWindow", "Bis:"))
        self.analyze_button.setText(_translate("MainWindow", "Daten verarbeiten und Anzeigen"))

    def increment_changed(self, state):
        if state == 0:
            self.to_date.setEnabled(False)
        else:
            self.to_date.setEnabled(True)

    def from_time_changed_analyze(self):
        # Check if from time is smaller than to time and set to time higher if necessary
        from_date = self.from_date_analyze.date()
        if from_date.daysTo(self.to_date_analyze.date()) < 0:
            self.to_date_analyze.setDate(from_date)

    def from_time_changed(self):
        # Check if from time is smaller than to time and set to time higher if necessary
        from_date = self.from_date.date()
        if from_date.daysTo(self.to_date.date()) < 0:
            self.to_date.setDate(from_date.addDays(1))
            
    def download_files(self):
        self.ddc.download_files(self.from_date.date().year(), self.from_date.date().month(), self.from_date.date().day(), self.from_date.date().daysTo(self.to_date.date()), self.increment_checkbox.isChecked())

    def delete_files(self):
        self.ddc.delete_files()
        
    def load_files_into_database(self):
        self.ddc.insert_files_into_database()
    
    def analyze_data(self):
        self.ddc.start_evaluation(self.from_date_analyze.date().toPyDate(), self.to_date_analyze.date().addDays(1).toPyDate())

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

